language: node_js
node_js:
- lts/*
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: 3wX5pxRMRCIKhri1jAOD66aty6Ba/gUoqkayPBZmxFM/RvbX63cRen5x84qhkTSbwh/iyrJ7GyllDN3L2ZNdGqmMKl2U8ruwnvFPGK3Jyn6oUQgXMaj3lPBv/9DKGe+o8nRnmrZh/NHaZdEN64YoMT3DReQeyn+0ATzzUU+f5PugZTA5uYBkFn06aV8gSVjTeLuvNdqx80Yv7KYtfkTMvQuaWUuwHBVXEAbkhNk9f1sA6+axNs87ZctP8cl8/gCVChVf28NiWnniZk/39NOQDi1mlzbeGUt0ovlw8thMKzMRLNJxAOCulnsvER7Heg3NPWXTLMEO31SQHeceG2l9/0NpABdrui978ePEqeXVS8scdXS2djWuIlWFlEFwYAw0VkFtfRx7iOlgXoovr+INO/xivw6qsQniVvxLFXvQWmZVD5CzYgm+Xl+Jk0vV6o90Wu1XvKO5ErZwgjod+Tpu/t3U/IXl1AY0YvlqjYJf1NGcBzLyK8whRS2Gd/orejn/jXbdM6z4BwqN4gaXWStxCU23Ol/NVHMuR1z9HfHYU6PGWREFw9wefjckcchZnxlIYn9RLVj/iQf24dJv90RaepVuXeiukFKCX49yIAvaQVZuVqYozV+lGvope5sIp86t2qqcTcbyKv6eVJbj3xbkALp6MjqYbgThYszvF78FFuA=
